default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

staging:
  <<: *default

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: events_calendar_development
  username: <%= ENV['DB_USERNAME'] %>

test:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: events_calendar_test
  username: <%= ENV['DB_USERNAME'] %>
